name: dart_ewelink_api
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/ianmaciel/dart_ewelink_api

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  json_annotation: ^4.5.0
  test: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
